version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    hostname:
      local.frontend.com
    environment:
      - CHOKIDAR_USEPOLLING=true